#ifndef NETWORKOUTPUT_GLOBAL_H
#define NETWORKOUTPUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKOUTPUT_LIBRARY)
#  define NETWORKOUTPUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETWORKOUTPUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKOUTPUT_GLOBAL_H
