Document: kaukkis
Title: Debian kaukkis Manual
Author: <insert document author here>
Abstract: This manual describes what kaukkis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kaukkis/kaukkis.sgml.gz

Format: postscript
Files: /usr/share/doc/kaukkis/kaukkis.ps.gz

Format: text
Files: /usr/share/doc/kaukkis/kaukkis.text.gz

Format: HTML
Index: /usr/share/doc/kaukkis/html/index.html
Files: /usr/share/doc/kaukkis/html/*.html

  
